# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20190723_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name=b'name',
            field=models.CharField(max_length=100),
        ),
    ]
