# Generated by Django 2.2.3 on 2019-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20190725_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ManyToManyField(related_name='img', to='frontend.Image'),
        ),
    ]
